(
  (id mirage)
  (name "Mirage")
  (ty Systems)
  (team (
    ((person "avsm") (role "project owner") (since "2009-"))
    ((person "rmortier") (role "project lead at Horizon") (since "2009-"))
    ((person "dscott") (role "project lead at Citrix") (since "2009-"))
    ((person "tgazagnaire") (role "project lead at OCamlPro") (since "2009-"))
    ((person "crotsos") (role "software defined networking") (since "2010-"))
    ((person "rproust") (role "linear typing") (since "2011-"))
    ((person "bsingh") (role "networking") (since "2011-"))
    ((person "gpali") (role "FreeBSD kernel port") (since "2012"))
    ((person "rwatson") (role "FreeBSD and MIPS/BERI") (since "2012-"))
    ((person "jcrowcroft") (role "professorial input") (since "2009-"))
    ((person "shand") (role "professorial input") (since "2009-"))
    ((person "dmcauley") (role "professor at Horizon") (since "2009-"))
    ((person "jludlam") (role "Xen Cloud Platfom integration") (since "2009-"))
    ((person "lkurth") (role "community management at xen.org") (since "2012-"))
    ((person "achaudhry") (role "xen.org incubation proposal") (since "2012-"))
 ))
)
